<input type="hidden" id="koalaExp" value="{{$userData->koalaExp}}" />
<input type="hidden" id="wallabyExp" value="{{$userData->wallabyExp}}" />
<input type="hidden" id="wombatExp" value="{{$userData->wombatExp}}" />
<input type="hidden" id="cockatooExp" value="{{$userData->cockatooExp}}" />
<input type="hidden" id="platypusExp" value="{{$userData->platypusExp}}" />
<input type="hidden" id="cassowaryExp" value="{{$userData->cassowaryExp}}" />
<input type="hidden" id="frogExp" value="{{$userData->frogExp}}" />
<input type="hidden" id="whaleExp" value="{{$userData->whaleExp}}" />
<input type="hidden" id="turtleExp" value="{{$userData->turtleExp}}" />
<input type="hidden" id="sharkExp" value="{{$userData->sharkExp}}" />
<input type="hidden" id="bilbyExp" value="{{$userData->bilbyExp}}" />
<input type="hidden" id="kangarooExp" value="{{$userData->kangarooExp}}" />